version: '3.4'

services:
  sql:
    container_name: todoApp_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@12345
  api:
    container_name: todoApp_api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "8001:443"
    depends_on:
      - sql
    
